# *Searching for the taxonomic classification of the protein JIP3: Predicting its Relatives*
All information and work from this assignment will be applied to classifying the scaffolding protein family JIP and its close relatives and familial history. Protein sequence information will be taken from BLAST (BLASTp). The reference figure is taken from Dietmar Kültz, Evolution of Osmosensory MAP Kinase Signaling Pathways, American Zoologist. 

## Introduction and Background 
JIP3 comes from the JIP family of MAPK scaffolding proteins. MAPK signaling affects axon susceptibility to pathological degeneration, yet the specific ways MAPK controls these outcomes are unknown. The JIP proteins have a scaffolding role in MAPK signaling. Little is known about the JIP scaffolding proteins, but JIP3, when inhibited, is found to slow down the degeneration of axons in response to injury or chemotherapy-induced neuropathy. Due to the need for more information on the function of the JIPs, constructing a taxonomic classification of the proteins would be a useful source of information. Another JNK interacting protein, JIP4, is a paralog of JIP3 and is involved in similar scaffolding roles. Although JIP3 has been shown to limit degeneration more than its other family members, the Summers lab continues to measure neurodegeneration conditions for each JIP protein, including inhibiting groups of JIP proteins at one time. 

To document and visualize the varying relatedness of each JIP protein, I created a phylogenetic tree with a list of proteins I predicted to be related to JIP3. The purpose of this is to develop a better understanding of its degenerative process by finding distant relatives through JIP3’s sequence and function. By providing a set of proteins similar in sequence, function, or both, they could serve as models of comparison for JIP3. Due to the limited information available on JIP3’s function and evolutionary relationships, this tree will serve as a foundation to explore other inhibition trials for comparison and possibly provide more ideas for experimental design for JIP3 observation based on these better-studied proteins. 

The article Evolution of Osomosensory MAP Kinase Signaling Pathways by Dietmar Kultz describes a study in which the author’s goal was to collect more information on the cellular integration of information via MAP kinases to supplement ideas about cell dynamics/adaptation. My project follows a different route in terms of the target protein. Still, the steps taken toward the goal are similar, involving the collection of evolutionary history and relationships to supplement the study of these protein processes.

![Reference Figure](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/az/41/4/10.1093/icb/41.4.743/2/m_i0003-1569-041-04-0743-f02.jpeg?Expires=1686027652&Signature=1Dg8aT8eB7wdMA-zHIinkffR1q6GRRKVOIBD-uDfOuRRDvE-HcYubwr3YOrEcnQZd0~r15qgba-99zWxluQuZfNc8rhw6itIfGgleoVS6Sw2yLDybSa7VLtvzS6bSTOsMHC8D-NbZJx89ovInn44SJr7wTP1m0XlK1MVTmmt~nG3eNyKNgK6D9W26ObcuTdXDhsX~oaxrje~Z1-q0Os6RrQDabF~u17egR0xT28VKE1YhP43IO9NuNyZeX0TLv3JUq3iktj53PLQrhoNdlEZlAL5Ri5GRzcVv-LI-U1ApglTN~Gmh2KjASziEk958FfGfWFN5BFqTHcTa7ikLyW6ug__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA)
**Fig 1. Radial phylogenic tree of MAP kinases from C. Elegans and H. Sapiens.** Side B shows paralogous MAP kinases in Homo Sapiens, and side A shows the same in Caenorhabditis elegans. The human tree shows examples of subfamilies within JNK whose activation is facilitated by the JIP proteins. The alignment and analysis process to create this comparison was meant to provide input about the evolutionary history of MAP kinases. 

## Reference 
Dietmar Kültz, Evolution of Osmosensory MAP Kinase Signaling Pathways, American Zoologist, Volume 41, Issue 4, August 2001, Pages 743–757, https://doi.org/10.1093/icb/41.4.743

## The Goal for Figure Reproduction
Kültz’s figure represents the main goal of my tree in that it demonstrates results that show both distantly related proteins, variations of protein families, and closely related proteins (not labeled but shown by nodes at the end of each branch). This figure is a good representation due to JIP3’s involvement in the DLK/MAPK signaling pathway in axons. It’s not part of the MAPK family but is instead a MAPK-interacting protein or a scaffolding protein, as mentioned above. It’s a rough representation of the goals for the JIP3 tree construction. Still, it provides the visual goal of looking at broad, evolutionary searches. It provides information about the protein families with which JIP3 interacts (and will be used as predictions for BLAST searches and 
alignment). 

## Materials and Methods 
### Data Acquisition 
The preliminary BLAST search for JIP3 relatives was done using PSI-BLAST, a tool specifically for looking at evolutionary relationships, to focus on regions of similarity and prevent the flooding of protein isoforms into the BLAST results: the function of the PSI-BLAST tool is to search for more distant relatives, which is what prevents the influx of isoforms. For the BLAST parameters, the database was limited to “RefSeq Select proteins” to narrow possible results from all sequences in BLAST-related repositories to ones that are more curated towards the protein of interest. All searches were limited to the homo sapien taxa. The FATSA sequence files for each tree input were downloaded through a BLASTp output or UniProt. Each input on the tree was chosen due to its proposed relationship to JIP3 or its possible functional similarities to JIP3:
**Rho Guanine nucleotide exchange factor 17:** By using PSI-BLAST to search the specific segments of JIP3’s conserved domains, the domain WD40_2 was the only one to produce a protein rather than a set of Jun terminal kinase interacting protein isoforms and shared JIP4: Paralog to JIP3 cited as serving a similar scaffolding function in both neurodegeneration and excess axonal lysosome accumulation prevention. 
**JNK:** JIP3 is a JNK-interacting protein, and so I predicted it might share commonalities due to areas of interaction or binding between the two.
**Cytoplasmic Dynein 1 Light Intermediate Chain 1:** This protein binds to the N-terminal of a JIP3 RH1 domain to prevent the accumulation of lysosomes in axons. The exact function of the protein is unknown in this process, so it’s possible to share some sequence similarities to JIP3 as they’re assumed to carry out the same axonal process. 
**Rab-Interacting Lysosomal Protein:** This protein is a component of the cytoplasmic dynein 1 complex mentioned above. The protein is described as having scaffolding/structure-like roles in the complex, linking dynein cargos and adaptor proteins, which could prove similar to JIP3’s poorly known role in lysosome accumulation prevention. 
**Myosin-13 and Lamin B2:**  These two proteins were the result of a BLAST search comparing the input for JIP3 and JNK. Lamin has a similar job to JIP3 as it serves as a framework for the nuclear envelope's function. Myosin has a similar structural role in structuring/remodeling axons and dendrites. 

### Tree Construction 

After compiling the sequence data into one FASTA file, I uploaded the data to NGPhylogeny through the tool's "one-click" portal. I used NGPhylogeny to align my sequences and construct my tree. Before identifying the tree useful in my analysis, I looked through the alignment viewer to ensure valid conservation points across the proteins. Due to some unfavorable results from the placement of JIP3 on the tree, I chose not to select an outgroup for the tree to appear rooted. 

## Results and Discussion
![Final Figure](C:\Users\ellen\Pictures\Final Comp Project Image.png)
**Fig 2. The Phylogenetic Depction Comparing JIP3 and its Possible Functional Relatives:**
NGPhylogeny constructed the phylogenetic tree based on selected FASTA input sequences. Names have been changed from BLAST/Uniprot labels to conventional ones (original names can be found on GitHub). “C Jun amino-terminal kinase interacting protein” 3 or 4 refers to JIP3 and JIP4, both of which appear like an outgroup to the other inputs at the top of the tree. All are homo sapiens. 

The initial BLAST for JIP3 provided limited results, with the only non-isoform hit being the rho guanine nucleotide exchange factor. The relationship between the rho guanine exchange factor and JIP3 is apparent on the tree, with them being the closest branches. Due to my inclusion of the JIP3 paralog, and JIP4, the two aren’t properly branched from one another due to their strong similarity. Therefore, based on this tree, it can be inferred that these two proteins share the same relationship with the other proteins represented. 

Due to the issues with standard BLASTp only showing isoforms and PSI-BLAST providing limited results, I looked into literature about or including JIP3 to determine a handful of proteins with similar functions or possibly similar sequences which would still be beneficial to have as a very general map of some evolutionary history. Most surprising was the distance between Lamin B2 and JIP3, as the two serve almost identical functions of support/scaffolding. Another find was the relationship of JNK versus Cytoplasmic Dynein to JIP3. Although the difference may be small, JNK shows closer relation to JIP3, which may provide reasoning to explore more JNK processes before lysosome accumulation prevention. JNK could be explored in neurodegeneration and any other function (beyond axons) that may require scaffolding and provide a template for JNK and JIP3 interaction. Finally, Myosin and Lamin were interesting findings when comparing JNK and JIP3 and could be further explored based on their similarities in structural function.

## Conclusion 
Figure 2 proves reproducible. Both the GitHub repository and the paper provide enough information for a second party to produce the same phylogenetic tree. The repository data entry contains all protein accession numbers for BLAST. BLAST parameters are listed and explained, and the paper provides enough information on the common protein name to conduct a Uniprot search and find the correct primary accession number. Unless sequences are changed or updated in the repository, results should look the same when aligned through NGPhylogeny or default muscle and translated into a tree based on maximum likelihood. 

In comparing the goal figure, Figure 1, to the final figure, Figure 2, there were some areas of reproduction. Still, I could not reproduce the figure to the extent explained in the “Goal for Figure Reproduction” section. It would have been more successful for the goal reproducibility to choose a protein involved in neurodegeneration that falls under a better-defined family like MAPK or JNK. Still, I wanted to create a better understanding of a lesser-known protein.

The most important finding of the project is the relationship between JIP3 and the rho guanine nucleotide exchange factor. It’s not a component in the DLK degeneration pathway with which JIP3 is looked at from an injury-response pathway, so the rho guanine exchange factor would be an important model to explore in terms of its function and involvement in pathways similar to JIP3’s for axon health. 

The tree structure could have been more clumsy and consistent throughout each protein selection. A similar project would be useful with better data acquisition techniques that show consistency and better-supporting evidence for their selection in the phylogenetic tree.

## Reflection 
Although I learned a lot about BLAST searches and tree building, I don’t think my work is a good representation of my learning. I fell short when applying what I learned to my project, approaching roadblocks like too specific of results with apprehension rather than problem-solving. Although I can communicate some general findings, I think I should’ve explored a different approach to producing a figure relating to JIP3, focusing more on specifically its function as that information is lacking and would have been beneficial for my research and my lab’s research to have a better understanding of how to produce figures and even create code(s) which could be useful beyond just my project. I don’t think the tree I created will be able to serve the use I originally hoped for. 
